--drop tables
drop table phone;
drop table comp_naics;
drop table works;
drop table requires;
drop table position;
drop table company;
drop table takes;
drop table has_skill;
drop table person;
drop table core_skill;
drop table job_category;
drop table section;
drop table teaches;
drop table course;
drop table falls_under;
drop table knowledge_skill;
drop table nwcet;
drop table naics;